# Generated by Django 5.2.12 on 2026-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
