# Generated by Django 5.2.12 on 2026-03-23 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_idempotencykey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('event',), name='unique_notification_per_event'),
        ),
    ]
